### PR TITLE
Add man page

### PR DESCRIPTION
**Pull request by wezm**
This PR adds a man page. It uses a trick that [ripgrep](https://github.com/BurntSushi/ripgrep/tree/master/doc) uses to convert a Markdown file into man page for easier writing and maintenance.

Here's what it looks like rendered:

rendered fac man page

### CODE REVIEW

**Comment by mkchoi212** [comment]
This is awesome! Regarding the installation of the man page, is there a simple script we could whip up? Or do we usually just leave the installation to the user?

**Comment by wezm** [comment]
That's probably up to package maintainers. I added `fac` to the Arch User Repository and have a spot in the [PKGBUILD script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fac#n40) waiting for the man page :-)

**Comment by mkchoi212** [comment]
That's awesome! Thank you 👍

**Comment by mkchoi212** [comment]
@wezm Any updates?? I don't really know how to make sense of the website you linked to :p

**Comment by wezm** [comment]
I still think it's the concern of people packaging `fac` for their platforms. For example in the `PKGBUILD` file linked above, which describes how to build a package on Arch Linux I include the man page in the package. Similarly in the homebrew formula the formula would install the man page as part of the homebrew package. For example this line in the `ripgrep` formula: https://github.com/Homebrew/homebrew-core/blob/0ed3f5b8925b2b202dacd64412414783557ff216/Formula/ripgrep.rb#L28

**Comment by wezm** [comment]
> Is there any I can do to fix it??

Sorry, I'm not following. What do you think needs fixing?

**Comment by mkchoi212** [comment]
I completely misunderstood what you meant by 
> I still think it's the concern of people packaging fac for their platforms.

**Pull request merged**
